language: java
jdk:
  - oraclejdk8

script:
  - mvn clean package

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t recycle-thing .
  - docker push gzfeng/recycle-thing
