language: java
jdk:
  - oraclejdk8

script:
  - mvn clean package
  - ls -l
  - ls -lR | grep 'recycle-thing-service-1.0-SNAPSHOT.jar'

services:
  - docker

after_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t recycle-thing .
  - docker tag recycle-thing:RT1.0.0 gzfeng/recycle-thing
  - docker push gzfeng/recycle-thing:RT1.0.0
